/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1SplatRouteImport } from './routes/v1.$'
import { Route as SourcesNamespaceRouteImport } from './routes/sources.$namespace'
import { Route as McpSplatRouteImport } from './routes/mcp.$'
import { Route as SourcesAddPluginKeyRouteImport } from './routes/sources.add.$pluginKey'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNamespaceRoute = SourcesNamespaceRouteImport.update({
  id: '/sources/$namespace',
  path: '/sources/$namespace',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSplatRoute = McpSplatRouteImport.update({
  id: '/mcp/$',
  path: '/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesAddPluginKeyRoute = SourcesAddPluginKeyRouteImport.update({
  id: '/sources/add/$pluginKey',
  path: '/sources/add/$pluginKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/mcp/$': typeof McpSplatRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/v1/$': typeof V1SplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/mcp/$': typeof McpSplatRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/v1/$': typeof V1SplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof ToolsRoute
  '/mcp/$': typeof McpSplatRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/v1/$': typeof V1SplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/secrets'
    | '/tools'
    | '/mcp/$'
    | '/sources/$namespace'
    | '/v1/$'
    | '/sources/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/secrets'
    | '/tools'
    | '/mcp/$'
    | '/sources/$namespace'
    | '/v1/$'
    | '/sources/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/secrets'
    | '/tools'
    | '/mcp/$'
    | '/sources/$namespace'
    | '/v1/$'
    | '/sources/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecretsRoute: typeof SecretsRoute
  ToolsRoute: typeof ToolsRoute
  McpSplatRoute: typeof McpSplatRoute
  SourcesNamespaceRoute: typeof SourcesNamespaceRoute
  V1SplatRoute: typeof V1SplatRoute
  SourcesAddPluginKeyRoute: typeof SourcesAddPluginKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$namespace': {
      id: '/sources/$namespace'
      path: '/sources/$namespace'
      fullPath: '/sources/$namespace'
      preLoaderRoute: typeof SourcesNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$': {
      id: '/mcp/$'
      path: '/mcp/$'
      fullPath: '/mcp/$'
      preLoaderRoute: typeof McpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/add/$pluginKey': {
      id: '/sources/add/$pluginKey'
      path: '/sources/add/$pluginKey'
      fullPath: '/sources/add/$pluginKey'
      preLoaderRoute: typeof SourcesAddPluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecretsRoute: SecretsRoute,
  ToolsRoute: ToolsRoute,
  McpSplatRoute: McpSplatRoute,
  SourcesNamespaceRoute: SourcesNamespaceRoute,
  V1SplatRoute: V1SplatRoute,
  SourcesAddPluginKeyRoute: SourcesAddPluginKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
