// Generated by wrangler types (run `bun run cf-typegen` to regenerate)

declare namespace Cloudflare {
  interface Env {
    HYPERDRIVE: Hyperdrive;
    MARKETING: Fetcher;
    WORKOS_API_KEY: string;
    WORKOS_CLIENT_ID: string;
    WORKOS_COOKIE_PASSWORD: string;
    ENCRYPTION_KEY: string;
    NODE_ENV: string;
  }
}

interface Env extends Cloudflare.Env {}
